name: Rust CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always
  SQLX_OFFLINE: true
  DATABASE_URL: mysql://root:root@127.0.0.1:3306/rust_clean_architecture

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mariadb:latest
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: rust_clean_architecture
        ports:
          - 3306:3306
      maildev:
        image: djfarrelly/maildev
        ports:
          - 1081:80
          - 1025:25
    steps:
    - uses: actions/checkout@v3
    - name: Fmt
      run: cargo fmt
    - name: Clippy
      run: cargo clippy
    - name: Run tests
      run: cargo test --verbose -- --test-threads 1
    - name: Build
      run: cargo build --verbose
