[package]
edition = "2021"
name = "clean-architecture-domain"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clean-architecture-shared = {path = "../shared"}

async-trait = "0.1.68"
chrono = { version = "0.4.26", features = ["clock", "std", "serde"], default-features = false }
serde = { version = "1.0.164", features = ["derive"] }
thiserror = "1.0.40"
uuid = { version = "1.4.0", features = ["v4", "serde"] }
validator = { version = "0.16.1", features = ["derive"] }
tracing = "0.1.37"
tokio = { version = "1.29.0", features = ["rt", "macros"] }
