[package]
edition = "2021"
name = "clean-architecture-infrastructure"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clean-architecture-domain = {path = "../domain"}
clean-architecture-shared = {path = "../shared"}

# Axum
axum = { version = "0.6.18", features = ["headers"] }

# Tower
tower = { version = "0.4.13", features = ["timeout"] }
tower-http = { version = "0.4.1", features = ["cors", "fs", "request-id", "util"] }

# Hyper
hyper = "0.14.27"

# sqlx
sqlx = { version = "0.6.3", features = ["runtime-tokio-native-tls", "chrono", "mysql", "macros", "bigdecimal", "offline"] }

# Log
env_logger = "0.10.0"
log = "0.4.19"
tracing = "0.1.37"
tracing-appender = "0.2.2"
tracing-subscriber = { version = "0.3.17", features = ["registry", "env-filter", "fmt", "json"] }

async-trait = "0.1.68"
bytes = "1.4.0"
chrono = { version = "0.4.26", features = ["clock", "std", "serde"], default-features = false }
clap = { version = "4.3.9", features = ["cargo", "derive"] }
config = "0.13.3"
dotenvy = "0.15.7"
futures = "0.3.28"
http-auth-basic = "0.3.3"
jsonwebtoken = "8.3.0"
lazy_static = "1.4.0"
lettre = "0.10.4"
mime = "0.3.17"
rand = "0.8.5"
serde = { version = "1.0.164", features = ["derive"] }
serde_json = "1.0.99"
serde_urlencoded = "0.7.1"
sha2 = "0.10.7"
tera = "1.19.0"
thiserror = "1.0.40"
tokio = { version = "1.29.0", features = ["full"] }
uuid = "1.4.0"
validator = { version = "0.16.1", features = ["derive"] }
metrics = "0.21.0"
metrics-exporter-prometheus = "0.12.1"
